FROM centos:6

ARG ANSIBLE_VERSION

RUN set -x \
  && yum update -y \
  && yum install -y epel-release \
  && yum install -y \
         gcc \
         binutils \
         python \
         python-devel \
#         python-crypto \
         python-setuptools \
         openssl \
         openssl-devel \
         openssh \
         libffi-devel \
  && easy_install pip \
  && pip install PyCrypto \
  && if [ "${ANSIBLE_VERSION}" = "latest" ]; then pip install ansible; else pip install ansible\==${ANSIBLE_VERSION}; fi
